apiVersion: 1
datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: gitlab*
    isDefault: true
    url: "http://elasticsearch:9200"
    readonly: false
    jsonData:
      esVersion: 7.10.0
      maxConcurrentShardRequests: 5
      timeField: "created_at"